#!/usr/bin/env python3
"""Replace bare "Agrees" verdicts in the two-model ASR tables with the exact shared span(s).

  python3 novel-lab/tools/asr_spans.py holoen

For each table row whose verdict is exactly "Agrees", the first-model quote and the second-model excerpt are
compared word by word (case, punctuation and curly quotes normalized). If the whole first-model line occurs
contiguously in the excerpt, the verdict becomes "Shared span (computed): whole line". Otherwise the maximal
common runs of three or more words are listed and the row is marked "Partial (computed)", so a card may
quote only those runs. Writes research/audio-check/partial-spans.md listing every partial row.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def toks(s):
    s = s.replace("’", "'").replace("‘", "'").replace("…", " ")
    return [w for w in re.findall(r"[a-z0-9']+", s.lower()) if w.strip("'")]


def runs(a, b, minlen):
    """Maximal common contiguous runs of a in b (greedy, left to right over a)."""
    out, i = [], 0
    while i < len(a):
        best = 0
        for j in range(len(b)):
            k = 0
            while i + k < len(a) and j + k < len(b) and a[i + k] == b[j + k]:
                k += 1
            best = max(best, k)
        if best >= minlen:
            out.append(" ".join(a[i:i + best]))
            i += best
        else:
            i += 1
    return out


def main():
    proj = ROOT / "projects" / sys.argv[1]
    report = ["# Partial ASR agreements (computed)", "",
              "Rows where the second model shares only part of the first model's line. Cards may quote only the",
              "listed runs. Generated by `tools/asr_spans.py`.", ""]
    for f in sorted((proj / "research" / "audio-check").glob("*.md")):
        if f.name == "partial-spans.md":
            continue
        lines = f.read_text(encoding="utf-8").splitlines()
        changed = 0
        for n, line in enumerate(lines):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if line.startswith("|") and len(cells) >= 4 and cells[-1].startswith("**Partial (computed):**"):
                # already converted on an earlier run: keep it in the report, so re-running never drops rows
                report.append(f"- `{f.name}` {cells[1]}: first model {cells[0]} → {cells[-1].split(':** ', 1)[-1]}")
                continue
            if not line.startswith("|") or len(cells) < 4 or cells[-1] != "Agrees":
                continue
            first, second = cells[0], cells[-2]
            a, b = toks(first), toks(second)
            if not a:
                continue
            whole = any(b[j:j + len(a)] == a for j in range(len(b) - len(a) + 1))
            if whole:
                verdict = "**Shared span (computed):** whole line"
            else:
                rs = runs(a, b, 3 if len(a) >= 3 else len(a))
                verdict = ("**Partial (computed):** shared runs " + " … ".join(f'"{r}"' for r in rs)) if rs \
                    else "**No shared run of 3+ words (computed)**; do not quote"
                report.append(f"- `{f.name}` {cells[1]}: first model {first} → {verdict.split(':** ', 1)[-1]}")
            cells[-1] = verdict
            lines[n] = "| " + " | ".join(cells) + " |"
            changed += 1
        if changed:
            f.write_text("\n".join(lines) + "\n", encoding="utf-8")
            print(f"{f.name}: {changed} verdicts made explicit")
    (proj / "research" / "audio-check" / "partial-spans.md").write_text("\n".join(report) + "\n", encoding="utf-8")
    print(f"partial rows: {len(report) - 5}")


if __name__ == "__main__":
    main()
