#!/usr/bin/env python3
"""Relationship-web check: who names whom in the cast's [SW] Relationships fields.

    python3 tools/web_check.py holoen

Writes research/qa/relationship-web.md: a matrix of the cast (✓ = A's Relationships names B) and the list of
one-way ties (A names B, B does not name A). A one-way tie is a coverage question, not an error: the missing
side may simply have had no room or no documented collab. Graduates and affiliates are included; Relationships
are matched by full name, short names and the pair names in qa_packets.SHORT.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
import qa_packets  # noqa: E402


def web(project):
    proj = ROOT / "projects" / project
    files = qa_packets.load(proj)
    cast = [s for c in qa_packets.COHORTS.values() for s in c["characters"] if s in files]
    pats = {}
    for s in cast:
        words = {files[s]["name"]} | set(qa_packets.SHORT.get(s, []))
        words.discard("FUWAMOCO")  # the twins' shared name would mark both; matched separately below
        pats[s] = re.compile(r"(?<![\w-])(" + "|".join(re.escape(w) for w in sorted(words, key=len, reverse=True))
                             + r")(?![\w-])")
    names = {}
    for a in cast:
        rel = files[a]["sw"].get("Relationships", "")
        names[a] = {b for b in cast if b != a and (pats[b].search(rel) or
                    ("FUWAMOCO" in rel and b in ("Fuwawa-Abyssgard", "Mococo-Abyssgard")))}
    return files, cast, names


def main(project):
    files, cast, names = web(project)
    short = {s: (qa_packets.SHORT.get(s) or [files[s]["name"]])[0] for s in cast}
    out = ["# Relationship web (computed)", "",
           "Generated by `tools/web_check.py`. Row = the card whose [SW] Relationships is read; ✓ = it names the",
           "column's member. One-way ties are listed below: a coverage question, not automatically an error.", "",
           "| | " + " | ".join(short[s] for s in cast) + " |", "|---|" + "---|" * len(cast)]
    for a in cast:
        out.append(f"| **{short[a]}** | " + " | ".join("—" if a == b else ("✓" if b in names[a] else "")
                                                       for b in cast) + " |")
    one = sorted((a, b) for a in cast for b in names[a] if a not in names[b])
    out += ["", f"## One-way ties ({len(one)})", ""]
    out += [f"- {files[a]['name']} names {files[b]['name']}; {files[b]['name']}'s Relationships does not name "
            f"{files[a]['name']}." for a, b in one] or ["None."]
    lonely = [s for s in cast if not names[s]]
    if lonely:
        out += ["", "Cards whose Relationships name no other cast member: " + ", ".join(files[s]["name"] for s in lonely)]
    path = ROOT / "projects" / project / "research" / "qa" / "relationship-web.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(cast)} cast, {sum(len(v) for v in names.values())} named ties, {len(one)} one-way → {path.relative_to(ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
